apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: webapp
  labels:
    name: containers-my-app
    release: prom
  namespace: default
spec:
  namespaceSelector:
    matchNames:
    - default
  selector:
    matchLabels:
      name: containers-my-app
  podMetricsEndpoints:
  - port: webapp
