apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  namespace: default
  labels:
    app: mysqld-exporter
    release: gym-data-tracker
spec:
  selector:
    app: mysql-server
    release: gym-data-tracker
  ports:
    - name: mysql
      protocol: TCP
      port: 3306
      targetPort: 3306
    - name: metrics
      protocol: TCP
      port: 9104
      targetPort: metrics
  type: ClusterIP
