apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-server
spec:
  selector:
    matchLabels:
      app: mysql-server
      release: gym-data-tracker
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql-server
        release: gym-data-tracker
    spec:
      containers:
      - image: mysql:5.7
        name: mysql-server
        args:
          - "--ignore-db-dir=lost+found"
        resources:
          limits:
            memory: "512Mi"
            cpu: "1500m"
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-root-pass
              key: password
        ports:
        - containerPort: 3306
          name: mysql-server
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: mysql-data
      - image: prom/mysqld-exporter
        name: mysqld-exporter
        args:
          - "--config.my-cnf=/etc/mysqld-exporter/.my.cnf"
        volumeMounts:
          - name: mysqld-exporter-config
            mountPath: /etc/mysqld-exporter/
        ports:
        - containerPort: 9104
          name: metrics
      volumes:
      - name: mysqld-exporter-config
        configMap:
          name: mysqld-exporter-config
      - name: mysql-data
        persistentVolumeClaim:
          claimName: mysql-data
