apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: webapp
  labels:
    name: containers-my-app
    release: test
  namespace: default
spec:
  namespaceSelector:
    matchNames:
    - default
  endpoints:
  - port: http
  selector:
    matchLabels:
      name: containers-my-app
      release: test
