apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
  labels:
    name: containers-gym-data-tracker-app
  namespace: default
spec:
  selector:
    matchLabels:
      name: containers-gym-data-tracker-app
  template:
    metadata:
      labels:
        name: containers-gym-data-tracker-app
    spec:
      containers:
      - name: app
        image: 927315517716.dkr.ecr.us-west-2.amazonaws.com/seshsrepo:gym-data-tracker-app-v${VERSION}
        ports:
        - containerPort: 8080
          name: webapp
        env:
        - name: MYSQL_USER
          value: "root"
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-root-pass
              key: password
        - name: MYSQL_SERVICE_HOST
          value: "mysql-service.default.svc.cluster.local"
        - name: MYSQL_SERVICE_PORT
          value: "3306"
        - name: MYSQL_DATABASE
          value: "gymdata"
