apiVersion: v1
kind: Service
metadata:
  name: webapp
  labels:
    name: containers-gym-data-tracker-app
  namespace: default
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 5000
  selector:
    name: containers-gym-data-tracker-app
