apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: webapp
  labels:
    name: containers-gym-data-tracker-app
    release: gym-data-tracker
  namespace: default
spec:
  namespaceSelector:
    matchNames:
    - default
  selector:
    matchLabels:
      name: containers-gym-data-tracker-app
      release: gym-data-tracker
  podMetricsEndpoints:
  - port: webapp
