apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: webapp
  labels:
    name: containers-gym-data-tracker-app
    release: gym-data-tracker
  namespace: default
spec:
  namespaceSelector:
    matchNames:
    - default
  endpoints:
  - port: http
  selector:
    matchLabels:
      name: containers-gym-data-tracker-app
      release: gym-data-tracker
